package main

import (
	"Projekat/App"
	"fmt"
)

func main() {
	app := App.CreateApp()

	app.Put("kljuc01", []byte("vrednost1"))
	app.Put("kljuc02", []byte("vrednost2"))
	app.Put("kljuc03", []byte("vrednost3"))
	app.Put("kljuc04", []byte("vrednost4"))
	app.Put("kljuc05", []byte("vrednost5"))
	app.Put("kljuc06", []byte("vrednost6"))
	app.Put("kljuc07", []byte("vrednost7"))

	app.Put("kljuc08", []byte("vrednost8"))
	app.Delete("kljuc03", []byte("vrednost3"))
	app.Put("kljuc10", []byte("vrednost10"))
	app.Put("kljuc11", []byte("vrednost11"))
	app.Put("kljuc12", []byte("vrednost12"))
	app.Put("kljuc13", []byte("vrednost13"))
	app.Put("kljuc14", []byte("vrednost14"))

	app.Delete("kljuc15", []byte("vrednost15"))
	app.Delete("kljuc05", []byte("vrednost5"))
	app.Delete("kljuc06", []byte("vrednost6"))
	app.Put("kljuc18", []byte("vrednost18"))
	app.Delete("kljuc08", []byte("vrednost08"))
	app.Put("kljuc20", []byte("vrednost20"))
	app.Put("kljuc21", []byte("vrednost21"))
	app.Put("kljuc30", []byte("vrednost30"))

	app.Put("kljuc23", []byte("vrednost23"))
	app.Put("kljuc24", []byte("vrednost24"))
	app.Put("kljuc25", []byte("vrednost25"))
	app.Put("kljuc26", []byte("vrednost26"))
	app.Put("kljuc27", []byte("vrednost27"))
	app.Put("kljuc01", []byte("vrednost01"))
	app.Put("kljuc28", []byte("vrednost28"))

	app.Put("kljuc31", []byte("vrednost31"))
	app.Put("kljuc32", []byte("vrednost32"))
	app.Put("kljuc33", []byte("vrednost33"))
	app.Put("kljuc34", []byte("vrednost34"))
	app.Put("kljuc35", []byte("vrednost35"))
	app.Put("kljuc36", []byte("vrednost36"))
	app.Put("kljuc37", []byte("vrednost37"))

	app.Put("kljuc08", []byte("vrednost8"))
	app.Delete("kljuc07", []byte("vrednost7"))
	app.Put("kljuc10", []byte("vrednost10"))
	app.Put("kljuc11", []byte("vrednost11"))
	app.Put("kljuc12", []byte("vrednost12"))
	app.Put("kljuc13", []byte("vrednost13"))
	app.Put("kljuc14", []byte("vrednost14"))

	app.Delete("kljuc15", []byte("vrednost15"))
	app.Delete("kljuc05", []byte("vrednost5"))
	app.Delete("kljuc06", []byte("vrednost6"))
	app.Put("kljuc18", []byte("vrednost18"))
	app.Delete("kljuc08", []byte("vrednost08"))
	app.Put("kljuc20", []byte("vrednost20"))
	app.Put("kljuc21", []byte("vrednost21"))
	app.Put("kljuc30", []byte("vrednost30"))

	app.Put("kljuc23", []byte("vrednost23"))
	app.Put("kljuc24", []byte("vrednost24"))
	app.Put("kljuc25", []byte("vrednost25"))
	app.Put("kljuc26", []byte("vrednost26"))
	app.Put("kljuc27", []byte("vrednost27"))
	app.Put("kljuc01", []byte("vrednost01"))
	app.Put("kljuc28", []byte("vrednost28"))

	app.Put("kljuc01", []byte("vrednost1"))
	app.Put("kljuc02", []byte("nova_vrednost2"))
	app.Put("kljuc03", []byte("vrednost3"))
	app.Put("kljuc04", []byte("vrednost4"))
	app.Put("kljuc05", []byte("vrednost5"))
	app.Put("kljuc06", []byte("vrednost6"))
	app.Put("kljuc07", []byte("vrednost7"))

	app.Put("kljuc08", []byte("vrednost8"))
	app.Delete("kljuc03", []byte("vrednost3"))
	app.Put("kljuc10", []byte("vrednost10"))
	app.Put("kljuc11", []byte("vrednost11"))
	app.Put("kljuc12", []byte("vrednost12"))
	app.Put("kljuc13", []byte("vrednost13"))
	app.Put("kljuc14", []byte("vrednost14"))

	app.Delete("kljuc15", []byte("vrednost15"))
	app.Delete("kljuc05", []byte("vrednost5"))
	app.Delete("kljuc06", []byte("vrednost6"))
	app.Put("kljuc18", []byte("vrednost18"))
	app.Delete("kljuc08", []byte("vrednost08"))
	app.Put("kljuc20", []byte("vrednost20"))
	app.Put("kljuc21", []byte("vrednost21"))
	app.Put("kljuc30", []byte("vrednost30"))

	app.Put("kljuc23", []byte("vrednost23"))
	app.Put("kljuc24", []byte("vrednost24"))
	app.Put("kljuc25", []byte("vrednost25"))
	app.Put("kljuc26", []byte("vrednost26"))
	app.Put("kljuc27", []byte("vrednost27"))
	app.Put("kljuc01", []byte("vrednost01"))
	app.Put("kljuc28", []byte("vrednost28"))


	_, value := app.Get("kljuc01")
	fmt.Println(string(value))
	_, value = app.Get("kljuc02")
	fmt.Println(string(value))
	_, value = app.Get("kljuc03")
	fmt.Println(string(value))
	_, value = app.Get("kljuc04")
	fmt.Println(string(value))
	_, value = app.Get("kljuc05")
	fmt.Println(string(value))
	_, value = app.Get("kljuc06")
	fmt.Println(string(value))
	_, value = app.Get("kljuc07")
	fmt.Println(string(value))
	_, value = app.Get("kljuc08")
	fmt.Println(string(value))
	_, value = app.Get("kljuc09")
	fmt.Println(string(value))
	_, value = app.Get("kljuc10")
	fmt.Println(string(value))
	_, value = app.Get("kljuc11")
	fmt.Println(string(value))
	_, value = app.Get("kljuc12")
	fmt.Println(string(value))
	_, value = app.Get("kljuc13")
	fmt.Println(string(value))
	_, value = app.Get("kljuc14")
	fmt.Println(string(value))
	_, value = app.Get("kljuc15")
	fmt.Println(string(value))
	_, value = app.Get("kljuc16")
	fmt.Println(string(value))
	_, value = app.Get("kljuc17")
	fmt.Println(string(value))
	_, value = app.Get("kljuc18")
	fmt.Println(string(value))
	_, value = app.Get("kljuc19")
	fmt.Println(string(value))
	_, value = app.Get("kljuc20")
	fmt.Println(string(value))
	_, value = app.Get("kljuc21")
	fmt.Println(string(value))
	_, value = app.Get("kljuc22")
	fmt.Println(string(value))
	_, value = app.Get("kljuc23")
	fmt.Println(string(value))
	_, value = app.Get("kljuc24")
	fmt.Println(string(value))
	_, value = app.Get("kljuc25")
	fmt.Println(string(value))
	_, value = app.Get("kljuc26")
	fmt.Println(string(value))
	_, value = app.Get("kljuc27")
	fmt.Println(string(value))
	_, value = app.Get("kljuc28")
	fmt.Println(string(value))
	_, value = app.Get("kljuc29")
	fmt.Println(string(value))
	_, value = app.Get("kljuc30")
	fmt.Println(string(value))
	_, value = app.Get("kljuc31")
	fmt.Println(string(value))
	_, value = app.Get("kljuc32")
	fmt.Println(string(value))
	_, value = app.Get("kljuc33")
	fmt.Println(string(value))
	_, value = app.Get("kljuc34")
	fmt.Println(string(value))
	_, value = app.Get("kljuc35")
	fmt.Println(string(value))
	_, value = app.Get("kljuc36")
	fmt.Println(string(value))
	_, value = app.Get("kljuc37")
	fmt.Println(string(value))

	app.StopApp()
}
